server:
  port: 8070

spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #allowMultiQueries=true는 mysql에서 다중쿼리 실행이 가능하도록 하는 옵션값(mssql, oracle은 이런 옵션이 없음)
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/todo?allowMultiQueries=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: bcgrhio
      password: 1q2w3e4r
      
logging:
  config: classpath:logback/logback-default.xml